### ISSUE TITLE
Callback Question

### ISSUE THREAD

**Issue by Colorado4Wheeler** [webdeck/homebridge-indigo2#3]
I must have missed this in the early development but can you clarify a process question for me?  

I'm working on totally reworked API and in testing I noticed that when HB sets a characteristic that even though I return the correct value in the return JSON that nothing happens in HomeKit, just a beachball, but if I send a request to you to update then it properly updates everything.

So when you set a characteristic, you do **not** process the returned JSON but instead wait until the plugin calls you to refresh and **then** you complete the process?

If that's the case then that would explain so many times that I've tweaked the code to try to keep devices from beach balling.  This will also greatly influence how I redevelop the package to handle requests.  

If this **is** the case, then could theoretically return an empty JSON record to you when you 'setCharacteristic' and it wouldn't matter, correct?

**Comment by Colorado4Wheeler** [comment]
I may have answered my own question.  I was using a device that had multiple requests to change different characteristics, once I set it to a simple switch it seems to take whatever is in the return JSON record.

This, however, does bring up another question: does a callback to the script to refresh overwrite it waiting for a response from the request?  For example, if I turn on the switch and it's taking, say, 5 seconds to respond back to the script but before that 5 seconds my plugin then makes a call to the script to refresh that same switch does the script abandon the first request because it just got a refresh?  Does it wait for the first to complete and then processes the second?  Does it ignore the second because the first is still waiting?

I know these may seem like odd questions but when I'm really playing with how the script reacts to things and I analyze the entire path of communications it seems like this is the case.

**Comment by Colorado4Wheeler** [comment]
This has been a very interesting test.  When I am faking this out and just return in the JSON the value requested for the characteristic then it takes 1-2 seconds and it updates.  If I do that exact same thing but with an immediate call back on top of that it updates almost instantly, like it's seeing the callback and abandoning processing the JSON that was returned.  

What makes this interesting is that when I tell it the characteristic changed in the return JSON and it processes for a couple seconds it works - it goes from on to off and off to on.  However when it is instant because I do a callback right away it also works even though the value is always off.  cmd=getInfo returns that this switch is off 100% of the time (in my test) while cmd=setCharacteristic forces the value to always be what the script requested and it also works 100% of the time but slower.

I know this is a rapid series of questions on here, I'm just trying to figure out how this thing works :).

**Comment by webdeck** [comment]
In reality everything is functional and multithreaded with callbacks all over the place, but I will describe as if it's a single thread.

User initiates a change through HomeKit:
1. Characteristic value update notification comes from homebridge.
2. I compare the new value to the value I have cached.
3. If the same, do nothing and return no error to homebridge.
4. If different, update my cached value to match the new value.
5. Call setCharacteristic request to HKB, wait for response.
6. If response is error, return error to homebridge.
7. If response is no error, parse the characteristics in the response.  For each characteristic, if the value is different from my cached value, update the value in my cache and update the value in homebridge to match.  Updating homebridge will kick off a series of events that notify HomeKit of the change.  Return no error after parsing all of the characteristics.

HKB calls REST endpoint /devices/ID:
1. Look up device ID - return 404 error if not found.
2. Call getInfo request to HKB, wait for response.
3. If response is error, return 500 error to HKB's /device/ID request.
4. If response  is no error, parse the characteristics in the response.  For each characteristic, if the value is different from my cached value, update the value in my cache and update the value in homebridge to match.  Updating homebridge will kick off a series of events that notify HomeKit of the change.  Return 200 to HKB's /device/ID request after parsing all of the characteristics.

Other notes:

Everything is multithreaded - events can be happening in parallel all over.  You can invoke the REST endpoints as much as you want.  I can be getting updates from homebridge all over the place.

However, my requests to HKB are serialized.  I never make more than one request at a time.  This is a holdover from homebridge-indigo, because the Indigo RESTful API couldn't handle too many requests in parallel - it would start returning errors.  All HKB requests are pushed onto a queue, and there is a single thread that issues the requests to HKB one at a time.  I can remove this limitation if you're able to handle an unlimited number of parallel requests - just say the word.

**Comment by webdeck** [comment]
BTW, with my Insteon lights, I don't see beachballs typically unless I keep turning the light off and on rapidly, and then it starts to fall behind but catches up when I stop tapping.  Everything is really quick on my system with HKB.

**Comment by Colorado4Wheeler** [comment]
Thanks for the breakdown.  So was that all in my head then, the callback to you doesn’t speed things up?  I’ll have to do some more playing around with that but it was a noticeable difference when I did a callback immediately when setCharacteristic was called rather than just let setCharacteristic do it’s thing.  

HKB’s performance is OK for me too, but one of the reasons for really playing with this is that I get timeouts for long operations such as opening curtains - not from the plugin or from Home/Eve but from Siri when I ask her to do it I always get “some of your devices are not responding” and I’m trying to see if I can work around that.  I may have to find a way to report back that when you are opening a drape that I utilize the ‘increasing’ and ‘decreasing’ characteristic values - perhaps that will alleviate the issue.

My biggest issue right now is the performance of pulling the initial device list is horrible and that’s a huge part of me wanting to rewrite this.  When I started it was fine but I saw that when I added characteristics it was just unacceptable and part of that was because I didn’t spend any time making the initial calls efficient.  Pretty soon I’m going to do some complex caching and updating so that when you call the API it’s absolutely instant - 100 devices in the blink of an eye.

I think at some point doing multiple requests would be interesting to try - however if Indigo’s API couldn’t handle it and I’m a child of Indigo’s architecture then it may not work.

**Comment by webdeck** [comment]
Everything is multithreaded, so HomeKit will get the characteristic value update when the earlier of these two things happens:

- I get a response from my setCharacteristic request
- You invoke /devices/ID with a different characteristic value.

Note however, that I update my cached value before I call setCharacteristic, so I if you invoke /devices/ID, and then my call back to you with getInfo returns the same characteristic value, it will match my cached value and therefore nothing gets sent to HomeKit as a result of that.  So, calling /devices/ID before returning the response to setCharacteristic shouldn't be any faster - it actually just creates another roundtrip that doesn't accomplish anything.  That's all assuming that you are returning the updated characteristic values in response to setCharacteristic.

**Comment by Colorado4Wheeler** [comment]
That’s how I assumed it happened before my tests, that I was just adding processing time but my test results confused me.
